name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - name: Run Vitest tests
        run: pnpm test
        working-directory: packages/core
