name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {}
jobs:
  release:
    permissions:
      contents: write  #  to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write  #  to create pull request (changesets/action)

    if: github.repository == 'akash-aman/dynamix-layout'

    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ci-setup
      - uses: ./.github/actions/ci-checks

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
          version: pnpm run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}